export const COVERAGE_CITIES = [
  { name: "Pinheiro", isHQ: true },
  { name: "Bequimão", isHQ: false },
  { name: "Goiabal Alcântara", isHQ: false },
  { name: "Peri Mirim", isHQ: false },
  { name: "Palmeirândia", isHQ: false },
  { name: "São Bento", isHQ: false },
  { name: "Santa Helena", isHQ: false },
  { name: "Turilândia", isHQ: false },
  { name: "Gov. Nunes Freire", isHQ: false },
  { name: "Maracaçumé", isHQ: false },
  { name: "Central do Maranhão", isHQ: false },
  { name: "Cururupu", isHQ: false },
  { name: "Pres. Sarney", isHQ: false },
];
