export const COVERAGE_CITIES = [
  { name: "Pinheiro", isHQ: true },
  { name: "Bequimao", isHQ: false },
  { name: "Goiabal Alcantara", isHQ: false },
  { name: "Peri Mirim", isHQ: false },
  { name: "Palmeirandia", isHQ: false },
  { name: "Sao Bento", isHQ: false },
  { name: "Santa Helena", isHQ: false },
  { name: "Turilandia", isHQ: false },
  { name: "Gov. Nunes Freire", isHQ: false },
  { name: "Maracacume", isHQ: false },
  { name: "Central do Maranhao", isHQ: false },
  { name: "Cururupu", isHQ: false },
  { name: "Pres. Sarney", isHQ: false },
];
